project:
  type: website
  output-dir: docs/
website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Please see left-sidebar for definitions"
    type: info
    position: below-navbar  
  title: "UMGCC FCSS"
  navbar:
    logo: images/hex.svg
    left:
    - text: "Home"
      href: https://umgccfcss.github.io/InstrumentQC/
    - text: "Levey-Jennings Plots"
      menu:
      - text: "Cytek Aurora 3L"
        href: https://umgccfcss.github.io/InstrumentQC/Aurora3L
      - text: "Cytek Aurora 4L"
        href: https://umgccfcss.github.io/InstrumentQC/Aurora4L
      - text: "Cytek Aurora 5L"
        href: https://umgccfcss.github.io/InstrumentQC/Aurora5L
      - text: "Cytek Aurora CS"
        href: https://umgccfcss.github.io/InstrumentQC/AuroraCS
      - text: "BD FACSCanto II "
        href: https://umgccfcss.github.io/InstrumentQC/CantoII
      - text: "BD LSR II"
        href: https://umgccfcss.github.io/InstrumentQC/LSRII
      - text: "BD FACSAria II"
        href: https://umgccfcss.github.io/InstrumentQC/AriaII
    - text: "Historical"
      menu:
      - text: "Cytek Aurora 3L"
        href: https://umgccfcss.github.io/Aurora3L/
      - text: "Cytek Aurora 4L"
        href: https://umgccfcss.github.io/Aurora4L/
      - text: "Cytek Aurora 5L"
        href: https://umgccfcss.github.io/Aurora5L/
      - text: "Cytek Aurora CS"
        href: https://umgccfcss.github.io/AuroraCS/
      - text: "BD FACSCanto II "
        href: https://umgccfcss.github.io/CantoII
      - text: "BD LSR II"
        href: index.qmd
      - text: "BD FACSAria II"
        href: https://umgccfcss.github.io/AriaII
    - text: "Year"
      menu:
      - text: "2017"
        href: Year2017.qmd
      - text: "2018"
        href: Year2018.qmd
      - text: "2019"
        href: Year2019.qmd
      - text: "2020"
        href: Year2020.qmd
      - text: "2021"
        href: Year2021.qmd
      - text: "2022"
        href: Year2022.qmd
      - text: "2023"
        href: Year2023.qmd
      - text: "2024"
        href: Year2024.qmd
    right:
    - text: "Help"
      href: https://umgccfcss.github.io/InstrumentQC/help
    - text: "Download Data"
      href: https://umgccfcss.github.io/InstrumentQC/Data
    - text: "Other"
      menu:
      - text: "Miscellaneous"
        href: https://umgccfcss.github.io/InstrumentQC/Miscellaneous
      - text: "QC Bead Lots"
        href: https://umgccfcss.github.io/InstrumentQC/CytekQCBead
    - icon: github
      href: https://github.com/UMGCCFCSS/InstrumentQC
      aria-label: GitHub
  page-footer:
    background: light
    left: University of Maryland, Baltimore
    right: Built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss